config/routes.rb
EstruturaBase::Application.routes.draw do
  root :to => "home#index"

  get '/contatos' => 'contatos#index',:as => 'contato'
  post '/contatos/enviar' => 'contatos#enviar'

  match '/admin/home/:id/enabled_disabled' => "admin/home#enabled_disabled"
  match '/admin/home/disabled_all/:modelo/:ids' => "admin/home#disabled_all"
  match '/admin/home/delete_all/:modelo/:ids' => "admin/home#delete_all"

  devise_for :users,:controllers => {
                        :sessions => "admin/sessions",
                        :unlocks => "admin/unlocks",
                        :passwords => "admin/passwords"
                      }
  namespace :admin do
    root :to => "home#index"

    resources :users
    resources :owners do
      get 'delete_image',:on => :member
    end

    resources :home do
      post 'set_session',:on => :collection
      post 'enabled_disabled',:on => :member
    end

    resources :four_oh_fours,:only => [:index,:show,:destroy]

    resources :locations do
      get 'delete_image',:on => :member
    end

    resources :menus do
      collection do
        get 'ordenar_menus'
        get 'sort'
      end
    end

    resources :permissions do
      get 'find_actions_by_model',:on => :collection
    end

    resources :roles do
      collection do
        get 'menus'
        get 'sub_menus'
      end
    end

    resources :sub_menus do
      collection do
        get 'ordenar_sub_menus'
        get 'sort'
        get 'find_sub_menus_by_menu'
      end
    end

    resources :dashboards

    match '*path' => 'four_oh_fours#add_request'

  end

end

app/models/report_error.rb
class ReportError < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/report_errors_controller.rb
# coding: utf-8
class Admin::ReportErrorsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!

  def index
    @report_errors = ReportError.where("name LIKE ?","%#{params[:search]}%")
                  .order("#{$order} #{$ordem}")
                  .paginate(:per_page => params[:per_page],:page => params[:page])
    @count = @report_errors.size
    respond_with @report_errors,:location => admin_report_errors_path
  end

  def show
    @report_error = ReportError.find(params[:id])
    respond_with @report_error,:location => admin_report_error_path
  end

  def new
    @report_error = ReportError.new
    respond_with @report_error,:location => new_admin_report_error_path
  end

  def edit
    @report_error = ReportError.find(params[:id])
  end

  def create
    @report_error = ReportError.new(params[:report_error])
    flash[:notice] = 'Erro reportado criada com sucesso!' if @report_error.save
    respond_with @report_error,:location => new_admin_report_error_path
  end

  def update
    @report_error = ReportError.find(params[:id])
    flash[:notice] = 'Erro reportado atualizado com sucesso!' if @report_error.update_attributes(params[:report_error])
    respond_with @report_error,:location => admin_report_errors_path
  end

  def destroy
    @report_error = ReportError.find(params[:id])
    flash[:notice] = 'Erro reportado deletado com sucesso' if  @report_error.destroy
    respond_with @report_error ,:location => admin_report_error_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/four_oh_fours/_form.html.erb
<%= form_for [:admin,@four_oh_four] do |f| %>
  <%= error_message_for(@four_oh_four) %>

  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :referer %><br />
    <%= f.text_field :referer %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/four_oh_fours/edit.html.erb
<h1>Editing four_oh_four</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_four_oh_four_path @four_oh_four %> |
<%= link_to 'Back', admin_four_oh_fours_path %>

app/views/admin/four_oh_fours/new.html.erb
<h1>New four_oh_four</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_four_oh_fours_path %>

app/views/admin/home/reportar_erro.html.erb
<% form_for @erro, :url => enviar_erro_path do |f| -%>
	<% table_form_model(@erro, :model_name => "do Erro", :style => "style='width:740px;'") do |e| %>
		<%= field_for_form(f, e, :erro) %>
		<%= field_for_form(f, e, :mensagem, { :field_type => :text }, { :rows => 10 }) %>
		<%= submit_for_form(f, "Enviar erro") %>
	<% end %>
<% end -%>

app/views/admin/report_errors/_form.html.erb
<%= form_for(@report_error) do |f| %>
  <%= error_message_for(@report_error) %>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/report_errors/edit.html.erb
<h1>Editing report_error</h1>

<%= render 'form' %>

<%= link_to 'Show', @report_error %> |
<%= link_to 'Back', report_errors_path %>

app/views/admin/report_errors/index.html.erb
<h1>Listing report_errors</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @report_errors.each do |report_error| %>
  <tr>
    <td><%= report_error.user %></td>
    <td><%= report_error.name %></td>
    <td><%= report_error.content %></td>
    <td><%= link_to 'Show', report_error %></td>
    <td><%= link_to 'Edit', edit_report_error_path(report_error) %></td>
    <td><%= link_to 'Destroy', report_error, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report error', new_report_error_path %>

app/views/admin/report_errors/new.html.erb
<h1>New report_error</h1>

<%= render 'form' %>

<%= link_to 'Back', report_errors_path %>

app/views/admin/report_errors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @report_error.user %>
</p>

<p>
  <b>Name:</b>
  <%= @report_error.name %>
</p>

<p>
  <b>Content:</b>
  <%= @report_error.content %>
</p>


<%= link_to 'Edit', edit_report_error_path(@report_error) %> |
<%= link_to 'Back', report_errors_path %>

app/views/admin/roles/_sub_menus_for_menu_permission.html.erb
<%= check_box_for_form(@sub_menus,@role,SubMenu,@role.sub_menus,
            :container_id => "sub_menus_for_menu_permission_role_id_#{@menu.id}",
            :legend => "Selecione os sub-menus do menu : <b>#{@menu.name}</b> para dar as permissões") %>

app/views/admin/roles/find_sub_menus_by_menu.js.erb
$(document).ready(function(){
  $('#sub_menus_for_menu_permission').append(
    "<%= escape_javascript(render 'sub_menus_for_menu_permission',
    :collection => @sub_menus,:role => @role,:menu => @menu)%>"
  )
})

app/views/admin/users/show.html.erb
<div class="info">
<h2><%= @user.name %></h2>
<%= show_field(@user,:username) %>
<%= show_field(@user,:email) %>
</div>